version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=hackaton
  
  web:
    build: .
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=hackaton
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=19d25e094faa2ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    command: uvicorn back.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres